import { Plugin, TFile, Notice } from "obsidian";
import { processTemplate } from "./templater";
import {
  BasesTemplateSettings,
  DEFAULT_SETTINGS,
  BasesTemplateSettingTab,
} from "./settings";

export default class BasesTemplatePlugin extends Plugin {
  /**
   * Merges original frontmatter properties back into the file after template application.
   * Properties from originalProperties take priority over template defaults.
   * This preserves filter-set properties from Bases (e.g., when creating from a filtered view).
   */
  async mergePropertiesAfterTemplate(
    file: TFile,
    originalProperties: Record<string, any>
  ) {
    // Wait for template to be fully applied and metadata cache to update
    await new Promise((resolve) => setTimeout(resolve, 200));
    
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    
    // Check if file has frontmatter
    if (lines[0] !== "---") return;
    
    // Find the end of frontmatter
    let endIndex = -1;
    for (let i = 1; i < lines.length; i++) {
      if (lines[i] === "---") {
        endIndex = i;
        break;
      }
    }
    
    if (endIndex === -1) return;
    
    // Get current frontmatter from metadata cache
    await this.app.metadataCache.getFileCache(file);
    const currentFm = this.app.metadataCache.getFileCache(file)?.frontmatter;
    
    if (!currentFm) return;
    
    // Merge: original properties override template properties
    // Skip 'position' metadata as it's auto-generated by Obsidian
    const mergedProperties: Record<string, any> = { ...currentFm };
    for (const [key, value] of Object.entries(originalProperties)) {
      if (key !== "position") {
        mergedProperties[key] = value;
      }
    }
    
    // Rebuild frontmatter section
    const newFrontmatterLines = ["---"];
    for (const [key, value] of Object.entries(mergedProperties)) {
      // Skip internal position property
      if (key === "position") continue;
      
      if (typeof value === "boolean") {
        newFrontmatterLines.push(`${key}: ${value}`);
      } else if (typeof value === "number") {
        newFrontmatterLines.push(`${key}: ${value}`);
      } else if (typeof value === "string") {
        newFrontmatterLines.push(`${key}: ${value}`);
      } else if (Array.isArray(value)) {
        newFrontmatterLines.push(`${key}:`);
        for (const item of value) {
          newFrontmatterLines.push(`  - ${item}`);
        }
      } else if (value === null) {
        newFrontmatterLines.push(`${key}: null`);
      } else {
        // Handle other types as string
        newFrontmatterLines.push(`${key}: ${value}`);
      }
    }
    newFrontmatterLines.push("---");
    
    // Reconstruct the file content
    const bodyLines = lines.slice(endIndex + 1);
    const newContent = [...newFrontmatterLines, ...bodyLines].join("\n");
    
    await this.app.vault.modify(file, newContent);
  }
  settings: BasesTemplateSettings;
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new BasesTemplateSettingTab(this.app, this));

    this.app.workspace.onLayoutReady(() => {
      this.registerEvent(
        this.app.vault.on("create", async (file: TFile) => {
          // Only process files that start with "Untitled" (created by Bases)
          if (!file.basename.startsWith("Untitled")) return;

          // Wait for metadata cache to be populated
          await new Promise((resolve) => setTimeout(resolve, 150));
          const fm = this.app.metadataCache.getFileCache(file)?.frontmatter;
          if (!fm) return;

          // Check the configured template property
          const value = fm[this.settings.templateProperty];
          if (!value) return;

          // Store original frontmatter properties (filter-set properties from Bases)
          // These should be preserved and take priority over template defaults
          const originalProperties = { ...fm };

          const values = Array.isArray(value) ? value : [value];
          const activeLeaf = this.app.workspace.getMostRecentLeaf();

          for (const item of values) {
            if (typeof item !== "string") continue;

            const link = item.match(/\[\[(.*?)\]\]/)?.[1];
            if (!link) continue;

            const templateFile = this.app.metadataCache.getFirstLinkpathDest(
              link,
              file.path
            );
            if (!templateFile) continue;

            const path = templateFile.path.toLowerCase();
            const templatesEnabled = !!(this.app as any).internalPlugins.plugins
              .templates?.enabled;
            const templaterEnabled = !!(this.app as any).plugins.plugins[
              "templater-obsidian"
            ];
            const templateFolder = (
              this.app as any
            ).internalPlugins.plugins.templates?.instance.options.folder?.toLowerCase();
            const templaterFolder = (this.app as any).plugins.plugins[
              "templater-obsidian"
            ]?.settings?.templates_folder?.toLowerCase();

            if (
              templatesEnabled &&
              templateFolder &&
              path.startsWith(templateFolder)
            ) {
              // Open the file temporarily in full screen to ensure it's the active file to apply the template
              // This is necessary until https://forum.obsidian.md/t/bases-applying-template-in-new-entry-popup-doesnt-apply-properties/105802 is solved
              if (activeLeaf === this.app.workspace.getMostRecentLeaf()) {
                await this.app.workspace.openLinkText(file.path, "", false);
              }
              await (
                this.app as any
              ).internalPlugins.plugins.templates.instance.insertTemplate(
                templateFile
              );
              await new Promise((resolve) => setTimeout(resolve, 100));
              // Merge back original properties after template application
              await this.mergePropertiesAfterTemplate(file, originalProperties);
            } else if (
              templaterEnabled &&
              templaterFolder &&
              path.startsWith(templaterFolder)
            ) {
              const processed = await processTemplate(this.app, templateFile);
              if (processed) {
                await this.app.vault.modify(file, processed);
                // Merge back original properties after template application
                await this.mergePropertiesAfterTemplate(file, originalProperties);
              }
            }
          }

          // if a new leaf was created, return to the original leaf and detach the new leaf
          const newLeaf = this.app.workspace.getMostRecentLeaf();
          if (activeLeaf && newLeaf && activeLeaf !== newLeaf) {
            newLeaf.detach();
          }
        })
      );
    });
  }

  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }

  async saveSettings() {
    await this.saveData(this.settings);
  }
}
